services:
  database:
    container_name: intuitive_care_database
    build:
      context: .
      dockerfile: .docker/Dockerfile
    environment:
      - POSTGRES_USER=intuitive_care
      - POSTGRES_PASSWORD=12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:
